### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by lucas-crodrigues** [lucas-crodrigues/ruby-capstone#29]
Project: https://github.com/lucas-crodrigues/ruby-capstone/projects/1
We're working as a group of three people
Team member 1: @jaferIdrees 
Team member 2: @lucas-crodrigues 
Team member 3: @nimplay 

Thank you.

**Comment by Nemwel-Boniface** [comment]
## Hello @lucas-crodrigues , @nimplay  and @jaferIdrees        :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] As you are a team of three, you are required to have cards for both the group tasks (Creating the items class cards) and also the individual tasks i.e the Book, MusicAlbum, and the Game classes tasks. Currently, I was only able to see the cards for the Group tasks and only the cards for Person 1 (The Book class). Kindly @nimplay and @lucas-crodrigues ensure that you include the cards for your tasks as well. This can be done by adding new cards and creating issues for them.

![image](https://user-images.githubusercontent.com/86318284/194920413-d9d80f4d-d557-47bd-91b6-7ec38da33629.png)

- [ ] For The first cards for the Book class @jaferIdrees task, it appears as though you just copied the contents from the first class (items) and pasted it here and did not bother to create a card for the Book class. 

**This is the specific task card I am talking about**

![image](https://user-images.githubusercontent.com/86318284/194920657-354bdde7-210b-428a-8f00-479c867201c1.png)

**This is what makes me conclude so**

![image](https://user-images.githubusercontent.com/86318284/194920802-0b72725a-50b4-4edc-968d-8f5a28c5c862.png)

**Note:** This specific task was meant to help you be able to handle yourself by practicing firsthand the technical knowhow of creating your own task cards and knowing how to manage a project given no clear guidelines. These are the skills that all employers are looking for in a developer. Doing things as you are demonstrating will come to haunt you in the job search where you find yourself having a lot of backlog and things to read within a short period of time.

I would advise you to be more serious with the tasks given at hand because I am personally ripping the benefits firsthand by having a unique skillset from my competitors. I would urge you the same as well.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucas-crodrigues** [comment]
Hello @Nemwel-Boniface, it appears you have clicked on Jafar's picture, and that filtered your results, as you can see there are 17 todo's, but only seven results, which means you're filtering them, mine and Nimrod's cards are also there.
Here's [Loom video](https://www.loom.com/share/5f287ef6189343b395c28237db1fcac8) illustrating what I mean.

**Comment by Nemwel-Boniface** [comment]
@lucas-crodrigues I have rechecked it right now. Kindly request a re-review. My apologies.

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
